#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = LAYOUT_split_3x5_3(
//    ┌───────────┬───────────┬───────────┬────────────┬────────────┐                       ┌─────────────┬────────────┬───────────┬───────────┬───────────┐
//    │     '     │     ,     │     .     │     p      │     y      │                       │      f      │     g      │     c     │     r     │     l     │
//    ├───────────┼───────────┼───────────┼────────────┼────────────┤                       ├─────────────┼────────────┼───────────┼───────────┼───────────┤
//    │ LGUI_T(a) │ LALT_T(o) │ LCTL_T(e) │ LSFT_T(u)  │     i      │                       │      d      │ RSFT_T(h)  │ RCTL_T(t) │ RALT_T(n) │ RGUI_T(s) │
//    ├───────────┼───────────┼───────────┼────────────┼────────────┤                       ├─────────────┼────────────┼───────────┼───────────┼───────────┤
//    │     ;     │     q     │     j     │     k      │     x      │                       │      b      │     m      │     w     │     v     │     z     │
//    └───────────┴───────────┼───────────┼────────────┼────────────┤                       ├─────────────┼────────────┼───────────┼───────────┴───────────┘
//                            │    esc    │ LT(1, spc) │ LT(2, tab) │                       │ LT(4, bspc) │ LT(3, ent) │    del    │                        
//                            └───────────┴────────────┴────────────┘                       └─────────────┴────────────┴───────────┘                        
  KC_QUOT      , KC_COMM      , KC_DOT       , KC_P          , KC_Y          ,                         KC_F           , KC_G          , KC_C         , KC_R         , KC_L        ,
  LGUI_T(KC_A) , LALT_T(KC_O) , LCTL_T(KC_E) , LSFT_T(KC_U)  , KC_I          ,                         KC_D           , RSFT_T(KC_H)  , RCTL_T(KC_T) , RALT_T(KC_N) , RGUI_T(KC_S),
  KC_SCLN      , KC_Q         , KC_J         , KC_K          , KC_X          ,                         KC_B           , KC_M          , KC_W         , KC_V         , KC_Z        ,
                                KC_ESC       , LT(1, KC_SPC) , LT(2, KC_TAB) ,                         LT(4, KC_BSPC) , LT(3, KC_ENT) , KC_DEL                                    
),

[1] = LAYOUT_split_3x5_3(
//    ┌──────┬─────────┬─────────┬───────┬────────┐                       ┌─────────┬──────┬──────┬──────┬────┐
//    │ undo │   cut   │  copy   │ paste │   no   │                       │   no    │ home │  up  │ end  │ no │
//    ├──────┼─────────┼─────────┼───────┼────────┤                       ├─────────┼──────┼──────┼──────┼────┤
//    │ lgui │  lalt   │  lctl   │ lsft  │ QK_REP │                       │ CW_TOGG │ left │ down │ rght │ no │
//    ├──────┼─────────┼─────────┼───────┼────────┤                       ├─────────┼──────┼──────┼──────┼────┤
//    │ boot │ DT_PRNT │ DT_DOWN │ DT_UP │   no   │                       │   no    │ pgup │  no  │ pgdn │ no │
//    └──────┴─────────┼─────────┼───────┼────────┤                       ├─────────┼──────┼──────┼──────┴────┘
//                     │   no    │  no   │   no   │                       │  bspc   │ ent  │ del  │            
//                     └─────────┴───────┴────────┘                       └─────────┴──────┴──────┘            
  KC_UNDO , KC_CUT  , KC_COPY , KC_PSTE , KC_NO  ,                         KC_NO   , KC_HOME , KC_UP   , KC_END  , KC_NO,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , QK_REP ,                         CW_TOGG , KC_LEFT , KC_DOWN , KC_RGHT , KC_NO,
  QK_BOOT , DT_PRNT , DT_DOWN , DT_UP   , KC_NO  ,                         KC_NO   , KC_PGUP , KC_NO   , KC_PGDN , KC_NO,
                      KC_NO   , KC_NO   , KC_NO  ,                         KC_BSPC , KC_ENT  , KC_DEL                   
),

[2] = LAYOUT_split_3x5_3(
//    ┌──────┬──────┬──────┬──────┬────┐                       ┌──────┬─────┬─────┬───┬────┐
//    │  ^   │  ,   │  .   │  %   │ no │                       │  no  │  1  │  2  │ 3 │ no │
//    ├──────┼──────┼──────┼──────┼────┤                       ├──────┼─────┼─────┼───┼────┤
//    │ lgui │ lalt │ lctl │ lsft │ =  │                       │  no  │  4  │  5  │ 6 │ 0  │
//    ├──────┼──────┼──────┼──────┼────┤                       ├──────┼─────┼─────┼───┼────┤
//    │  /   │  *   │  -   │  +   │ no │                       │  no  │  7  │  8  │ 9 │ no │
//    └──────┴──────┼──────┼──────┼────┤                       ├──────┼─────┼─────┼───┴────┘
//                  │  no  │  no  │ no │                       │ bspc │ spc │ del │         
//                  └──────┴──────┴────┘                       └──────┴─────┴─────┘         
  KC_CIRC , KC_COMM , KC_DOT  , KC_PERC , KC_NO  ,                         KC_NO   , KC_1   , KC_2   , KC_3 , KC_NO,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_EQL ,                         KC_NO   , KC_4   , KC_5   , KC_6 , KC_0 ,
  KC_SLSH , KC_ASTR , KC_MINS , KC_PLUS , KC_NO  ,                         KC_NO   , KC_7   , KC_8   , KC_9 , KC_NO,
                      KC_NO   , KC_NO   , KC_NO  ,                         KC_BSPC , KC_SPC , KC_DEL               
),

[3] = LAYOUT_split_3x5_3(
//    ┌───────────┬───────────┬───────────┬───────────┬──────┐                       ┌────┬──────┬──────┬──────┬──────┐
//    │     %     │     {     │     [     │     (     │  ^   │                       │ $  │  )   │  ]   │  }   │  ?   │
//    ├───────────┼───────────┼───────────┼───────────┼──────┤                       ├────┼──────┼──────┼──────┼──────┤
//    │ LGUI_T(\) │ LALT_T(/) │ LCTL_T(-) │ LSFT_T(=) │  ~   │                       │ !  │ rsft │ rctl │ ralt │ rgui │
//    ├───────────┼───────────┼───────────┼───────────┼──────┤                       ├────┼──────┼──────┼──────┼──────┤
//    │     #     │     *     │     +     │     _     │  @   │                       │ |  │  &   │  <   │  >   │  `   │
//    └───────────┴───────────┼───────────┼───────────┼──────┤                       ├────┼──────┼──────┼──────┴──────┘
//                            │    del    │    spc    │ bspc │                       │ no │  no  │  no  │              
//                            └───────────┴───────────┴──────┘                       └────┴──────┴──────┘              
  KC_PERC         , KC_LCBR         , KC_LBRC         , KC_LPRN        , KC_CIRC ,                         KC_DLR  , KC_RPRN , KC_RBRC , KC_RCBR , KC_QUES,
  LGUI_T(KC_BSLS) , LALT_T(KC_SLSH) , LCTL_T(KC_MINS) , LSFT_T(KC_EQL) , KC_TILD ,                         KC_EXLM , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI,
  KC_HASH         , KC_ASTR         , KC_PLUS         , KC_UNDS        , KC_AT   ,                         KC_PIPE , KC_AMPR , KC_LT   , KC_GT   , KC_GRV ,
                                      KC_DEL          , KC_SPC         , KC_BSPC ,                         KC_NO   , KC_NO   , KC_NO                      
),

[4] = LAYOUT_split_3x5_3(
//    ┌──────┬──────┬──────┬──────┬──────┐                       ┌────┬─────┬─────┬────┬──────┐
//    │  no  │  no  │  no  │  no  │  no  │                       │ f1 │ f2  │ f3  │ f4 │  f5  │
//    ├──────┼──────┼──────┼──────┼──────┤                       ├────┼─────┼─────┼────┼──────┤
//    │ vold │ mprv │ mnxt │ volu │  no  │                       │ f6 │ f7  │ f8  │ f9 │ f10  │
//    ├──────┼──────┼──────┼──────┼──────┤                       ├────┼─────┼─────┼────┼──────┤
//    │  no  │  no  │  no  │  no  │  no  │                       │ no │ f11 │ f12 │ no │ boot │
//    └──────┴──────┼──────┼──────┼──────┤                       ├────┼─────┼─────┼────┴──────┘
//                  │ mstp │ mply │ mute │                       │ no │ no  │ no  │            
//                  └──────┴──────┴──────┘                       └────┴─────┴─────┘            
  KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,                         KC_F1 , KC_F2  , KC_F3  , KC_F4 , KC_F5  ,
  KC_VOLD , KC_MPRV , KC_MNXT , KC_VOLU , KC_NO   ,                         KC_F6 , KC_F7  , KC_F8  , KC_F9 , KC_F10 ,
  KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,                         KC_NO , KC_F11 , KC_F12 , KC_NO , QK_BOOT,
                      KC_MSTP , KC_MPLY , KC_MUTE ,                         KC_NO , KC_NO  , KC_NO                   
)
};

bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case KC_A ... KC_Z:
        case KC_MINS:
            add_weak_mods(MOD_BIT(KC_LSFT));  // Apply shift to next key.
            return true;

        // Keycodes that continue Caps Word, without shifting.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
            return true;

        default:
            return false;  // Deactivate Caps Word.
    }
};

enum combo_events {
  CAPS_COMBO,
};

const uint16_t caps_combo[] PROGMEM = {KC_P, KC_G, COMBO_END};

combo_t key_combos[] = {
  [CAPS_COMBO] = COMBO_ACTION(caps_combo),
};

void process_combo_event(uint16_t combo_index, bool pressed) {
  switch(combo_index) {
    case CAPS_COMBO:
      if (pressed) {
        caps_word_on();  // Activate Caps Word!
      }
      break;
  }
}
