#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_3(KC_SCLN, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, LGUI_T(KC_A), LALT_T(KC_O), LSFT_T(KC_E), LCTL_T(KC_U), KC_I, KC_D, RCTL_T(KC_H), RSFT_T(KC_T), RALT_T(KC_N), RGUI_T(KC_S), KC_QUOT, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, LT(2,KC_ESC), LT(1,KC_SPC), LT(4,KC_TAB), LT(5,KC_BSPC), LT(3,KC_ENT), KC_DEL),
    [1] = LAYOUT_split_3x5_3(KC_UNDO, KC_CUT, KC_PSTE, KC_COPY, KC_NO, KC_NO, CW_TOGG, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, QK_REP, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO, KC_NO, KC_BSPC, KC_ENT, KC_DEL),
    [2] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_0, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_BSPC, KC_SPC, KC_DEL),
    [3] = LAYOUT_split_3x5_3(KC_PERC, KC_LBRC, KC_LCBR, KC_LPRN, KC_NO, KC_NO, KC_RPRN, KC_RCBR, KC_RBRC, KC_CIRC, KC_ASTR, KC_SLSH, KC_PLUS, KC_MINS, KC_NO, KC_NO, KC_EQL, KC_AMPR, KC_EXLM, KC_PIPE, KC_AT, KC_BSLS, KC_HASH, KC_UNDS, KC_NO, KC_NO, KC_DLR, KC_TILD, KC_QUES, KC_GRV, KC_DEL, KC_SPC, KC_BSPC, KC_NO, KC_NO, KC_NO),
    [4] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_MPLY, KC_MSTP),
    [5] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LGUI_T(KC_F1), LALT_T(KC_F2), LSFT_T(KC_F3), LCTL_T(KC_F4), KC_F5, KC_F6, RCTL_T(KC_F7), RSFT_T(KC_F8), RALT_T(KC_F9), RGUI_T(KC_F10), KC_NO, KC_NO, KC_NO, KC_F11, KC_NO, KC_NO, KC_F12, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM = LAYOUT_split_3x5_3('L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'R', 'R', 'R');
bool       get_chordal_hold(uint16_t tap_hold_keycode, keyrecord_t *tap_hold_record, uint16_t other_keycode, keyrecord_t *other_record) {
    // Exceptionally allow some one-handed chords for hotkeys.
    switch (tap_hold_keycode) {
        case LT(2, KC_ESC):
        case LT(1, KC_SPC):
        case LT(4, KC_TAB):
        case LT(5, KC_BSPC):
        case LT(3, KC_ENT):
            return true;
    }
    // Otherwise defer to the opposite hands rule.
    return get_chordal_hold_default(tap_hold_record, other_record);
}

bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case KC_A ... KC_Z:
            add_weak_mods(MOD_BIT(KC_LSFT)); // Apply shift to next key.
            return true;

        // Keycodes that continue Caps Word, without shifting.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case KC_MINS:
            return true;

        default:
            return false; // Deactivate Caps Word.
    }
}


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
